### ISSUE TITLE
Compact only within certain number of messages

### ISSUE THREAD

**Issue by jn64** [cbyrneee/CompactChat#11]
Love the mod but there's various situations where it's not so helpful. For example if you say a few "yes" and "no" in a conversation, compacting them makes the chat log lose context.

It would be useful to be able to compact only messages that are repeated within a certain distance. For example a distance of 1 would compact only consecutive messages, which would prevent spam but not affect any proper conversations.

Alternative solutions:

- Compact only within certain time
- Compact only system messages (not from a user)

**Comment by cbyrneee** [comment]
Good idea, I'll add an "expiry" timer. 

You'll be able to select between world rejoin and a specified number of minutes.

**Comment by cbyrneee** [comment]
Thank you for the feature request, @jn64!

Only compacting consecutive chat messages is now available in v1.3 of CompactChat, which you can download from [Modrinth](https://modrinth.com/mod/compactchat) or from the [releases page](https://github.com/cbyrneee/CompactChat/releases).
