### ISSUE TITLE
'Done' button in the config screen appears weirdly in fullscreen

### ISSUE THREAD

**Issue by Scarlaid** [cbyrneee/CompactChat#12]
In fullscreen
![image](https://user-images.githubusercontent.com/90851437/172015380-b3e8000f-ee5f-4f3a-9614-564543b1c8f8.png)

In windowed however, visually normal
![image](https://user-images.githubusercontent.com/90851437/172015369-e836ff90-9e9c-4f45-80d6-35e2fff58da6.png)

**Comment by cbyrneee** [comment]
Thanks for the report! Working on fixing this now, and a fix should be out within the coming days.

**Comment by cbyrneee** [comment]
This issue is fixed in the 1.19 branch of the mod, and I should have a new build for 1.18 coming out soon.
