### ISSUE TITLE
"Compact chat" making the chat "blank"

### ISSUE THREAD

**Issue by Scarlaid** [cbyrneee/CompactChat#15]
The two picture below will provide the issue, as how the title stated

The lastest version 
![image](https://user-images.githubusercontent.com/90851437/172059001-8336d835-e88b-49c5-9f14-86194c7e79ca.png)

The 1.1.1 version runs fine
![image](https://user-images.githubusercontent.com/90851437/172059119-13a1d690-2087-41a1-a29f-53a2fc83c0e2.png)

**Comment by cbyrneee** [comment]
What server is this on, @Scarlaid?

**Comment by Scarlaid** [comment]
its just my SMP man

**Comment by Scarlaid** [comment]
well, joining other servers also make the chat like that
![image](https://user-images.githubusercontent.com/90851437/172059494-f2612412-4bde-4f11-82bd-c03deff95dd6.png)

**Comment by cbyrneee** [comment]
Interesting, will look into it.

**Comment by cbyrneee** [comment]
Fixed in v1.2.1 - You can now download it on the releases page, or on modrinth.

Thank you for the bug report @Scarlaid!
