### ISSUE TITLE
Add an option to customize the chat brackets around a player's name

### ISSUE THREAD

**Issue by Scarlaid** [cbyrneee/CompactChat#17]
The vanilla chat layout is `<player> text`
In general, this looks really, bad, maybe for me only 😢
![image](https://user-images.githubusercontent.com/90851437/172648246-bc321cf3-4ac2-4573-a371-91a0b609a13d.png)

So I don't know if any mods existed to change the bracket, so here's my idea
If possible, any vanilla servers, still keeping the vanilla chat bracket, should be able to change to a different one like `player: text` 
![image](https://user-images.githubusercontent.com/90851437/172648904-0db02e69-043f-45ff-b535-2df6897424cd.png)

It may look not much of a change, but removing the <> do make the chat looks cleaner and more appealing as a chat.

**Comment by ShaneTRS** [comment]
As of 1.19, this is provided by the language file (you can simply change it with a server resourcepack). I personally think this is also out of scope for CompactChat. I haven't heard of another mod (clientside) aiming to re-format chat (which may be easier now in 1.19), but creating it under a different mod wouldn't be a bad idea imo.

**Comment by Scarlaid** [comment]
> As of 1.19, this is provided by the language file (you can simply change it with a server resourcepack). I personally think this is also out of scope for CompactChat. I haven't heard of another mod (clientside) aiming to re-format chat (which may be easier now in 1.19), but creating it under a different mod wouldn't be a bad idea imo.

I'm still using 1.18.2 because some of the mods I'm using isn't updated to 1.19 yet, thanks for the info for 1.19 though 😁

**Comment by cbyrneee** [comment]
As said by @ShaneTRS this is out of scope for our project, and can be changed via a resource pack for the last few versions of Minecraft.
