### ISSUE TITLE
Custom font breaks message counter

### ISSUE THREAD

**Issue by Felix14-v2** [cbyrneee/CompactChat#4]
[[Demo]](https://youtu.be/SQRcDlL0G08)

**To reproduce**
- Install resourcepack with custom font
- Use `/tellraw @a {"text":"<text>","font":"<font>"}` to get broken message
- UPD: this also works without resourcepacks but with missing font.

**Additional info**
[Example pack.zip](https://github.com/cbyrneee/CompactChat/files/7255355/Example.pack.zip)
Example command: `/tellraw @a {"text":"\u1238","font":"custom"}`

I think this can be fixed by applying default font to the counter ("font":"default").

**Comment by cbyrneee** [comment]
Thanks for the detailed report. I'll fix this in the coming days.

**Comment by cbyrneee** [comment]
Thank you, will be fixed in the next update.
